export enum ExceptionCodeEnum {
  FIRST_NAME_IS_REQUIRED = 'FIRST_NAME_IS_REQUIRED',
  LAST_NAME_IS_REQUIRED = 'LAST_NAME_IS_REQUIRED',
  USER_NAME_IS_REQUIRED = 'USER_NAME_IS_REQUIRED',
  PASSWORD_IS_REQUIRED = 'PASSWORD_IS_REQUIRED',
  UNAVAILABLE_USER_NAME = 'UNAVAILABLE_USER_NAME',
  INVALID_LOGIN = 'INVALID_LOGIN',
  AMOUNT_NEEDS_TO_BE_GREATER_THAN_ZERO = 'AMOUNT_NEEDS_TO_BE_GREATER_THAN_ZERO',
  USER_NOT_FOUND = 'USER_NOT_FOUND'
}
