export enum ExceptionCodeEnum {
  FIRST_NAME_IS_REQUIRED = 'FIRST_NAME_IS_REQUIRED',
  LAST_NAME_IS_REQUIRED = 'LAST_NAME_IS_REQUIRED',
  USER_NAME_IS_REQUIRED = 'USER_NAME_IS_REQUIRED',
  PASSWORD_IS_REQUIRED = 'PASSWORD_IS_REQUIRED'
}
